version: '3.1'

services:
  db:
    container_name: ${MYSQL_CONTAINER_NAME}
    image: mysql:8.0.17
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_HOST: ${MYSQL_ROOT_HOST}
      BASE_URL: ${BASE_URL}
      PORT: ${PORT}
    ports:
      - "3306:3306"
    volumes:
      - ./data:/docker-entrypoint-initdb.d
      - db_data:/var/lib/mysql

  app:
    container_name: node_app
    image: ghcr.io/max-pfi/contdel:v0.0.3
    ports:
      - "3000:3000"
    environment:
      MYSQL_HOST: db
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_HOST: ${MYSQL_ROOT_HOST}
      SESSION_SECRET: ${SESSION_SECRET}
      BASE_URL: ${BASE_URL}
      PORT: ${PORT}
    depends_on:
      - db
    volumes:
      - ./uploads:/usr/src/app/public/img/uploads

volumes:
  db_data: