name: CI/CD Workflow

on:
  push:
    branches:
      - master
    tags:
      - 'v*'
  pull_request:
    branches:
      - master

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run ESLint and save results
        run: npm run lint > eslint-report.txt

      - name: Upload ESLint results
        uses: actions/upload-artifact@v3
        with:
          name: eslint-results
          path: eslint-report.txt

      - name: Run Jest tests
        run: npm test -- --coverage --outputFile=test-report.json

      - name: Upload Jest coverage and test report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage/

          name: test-report
          path: test-report.json

  build:
    runs-on: ubuntu-latest
    needs: lint-and-test

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build